//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinVi.rc
//
#define ID_APPLY                        3
#define ABOUT_TEXTX                     13
#define ID_NEW                          100
#define ID_NEWVI                        101
#define ID_OPEN                         102
#define ID_SAVE                         103
#define ID_SAVEAS                       104
#define ID_ALTERNATE                    105
#define ID_READFILE                     106
#define ID_FILELIST                     107
#define ID_PRINT                        108
#define ID_PRINTSETTINGS                109
#define ID_EXIT                         110
#define ID_CUT                          111
#define ID_COPY                         112
#define ID_PASTE                        113
#define ID_DELETE                       114
#define ID_TAG                          115
#define ID_TAGBACK                      116
#define ID_INSMODE                      117
#define ID_REPMODE                      118
#define ID_CMDMODE                      119
#define ID_SELECTALL                    120
#define ID_REFRESH                      121
#define ID_HELP                         125
#define ID_WEBPAGE                      126
#define ID_ABOUT                        127
#define ID_FONT                         131
#define ID_COLORS                       132
#define ID_SETTINGS                     133
#define ID_DISPLAYSETTINGS              133
#define ID_EDITSETTINGS                 134
#define ID_WRAPSCROLL                   135
#define ID_LANGUAGE                     136
#define ID_UNDO                         141
#define ID_OEM                          151
#define ID_ANSI                         152
#define ID_UTF8                         153
#define ID_UTF16                        154
#define ID_UTF16LE                      155
#define ID_UTF16BE                      156
#define ID_EBCDIC                       157
#define ID_HEX                          158
#define ID_COMMAND                      161
#define ID_SEARCH                       171
#define ID_SRCHAGN                      172
#define IDS_VERSION                     200
#define IDS_VERSIONBITS                 201
#define IDS_VERSIONTITLE                202
#define IDS_AUTHOR                      203
#define IDS_WEBADDRESS                  204
#define IDS_COMPILER                    205
#define IDD_SETTINGS                    300
#define IDD_EDITSETTINGS                301
#define IDD_DISPLAYSETTINGS             302
#define IDD_ABOUT                       305
#define IDD_SEARCH                      306
#define IDD_ARGS                        307
#define IDD_COLORS                      308
#define IDD_PRINTSETTINGS               309
#define IDD_PRINTCANCEL                 310
#define IDD_LANGUAGE                    311
#define IDD_WRAP_SCROLL                 312
#define IDD_SUBSTCONFIRM                313
#define IDC_BREAKLINES                  1001
#define IDC_TERSE                       1002
#define IDC_WRAPSCAN                    1003
#define IDC_IGNORECASE                  1004
#define IDC_LOWERCASE                   1005
#define IDC_PAGE_THRESHOLD              1006
#define IDC_AUTORESTORE                 1007
#define IDC_NUMBER_OF_BACKUPS           1007
#define IDC_TABSTOP                     1008
#define IDC_SHIFTWIDTH                  1009
#define IDC_AUTOINDENT                  1010
#define IDC_READONLY                    1011
#define IDC_STORE                       1012
#define IDC_SEARCHSTRING                1013
#define IDC_SHOWREPLACE                 1014
#define IDC_MAGIC                       1015
#define IDC_MATCHCASE                   1016
#define IDC_WHOLEWORD                   1017
#define IDC_REPLACESTRING               1018
#define IDC_REPLACE                     1019
#define IDC_REPLACEALL                  1020
#define IDC_FORWARD                     1021
#define IDC_BACKWARD                    1022
#define IDC_LISTBOX                     1022
#define IDC_SHOWMATCH                   1023
#define IDC_AUTOWRITE                   1024
#define IDC_DEFAULTINSERT               1025
#define IDC_COLOR0                      1027
#define IDC_COLOR1                      1028
#define IDC_COLOR2                      1029
#define IDC_COLOR3                      1030
#define IDC_COLOR4                      1031
#define IDC_COLOR5                      1032
#define IDC_COLOR6                      1033
#define IDC_COLOR7                      1034
#define IDC_COLOR8                      1035
#define IDC_COLOR9                      1036
#define IDC_COLOR10                     1037
#define IDC_COLOR11                     1038
#define IDC_COLOR12                     1039
#define IDC_COLOR13                     1040
#define IDC_COLOR14                     1041
#define IDC_COLOR15                     1042
#define IDC_EDIT_BG                     1043
#define IDC_EDIT_FG                     1044
#define IDC_SELECT_BG                   1045
#define IDC_SELECT_FG                   1046
#define IDC_PAREN_BG                    1047
#define IDC_PAREN_FG                    1048
#define IDC_NEWLINE_FG                  1049
#define IDC_COLORS                      1050
#define IDC_SYSTEM                      1051
#define IDC_CUSTOM                      1052
#define IDC_BITMAP                      1053
#define IDC_FRAME0                      1055
#define IDC_FRAME1                      1056
#define IDC_FRAME2                      1057
#define IDC_FRAME3                      1058
#define IDC_FRAME4                      1059
#define IDC_FRAME5                      1060
#define IDC_FRAME6                      1061
#define IDC_BITMAPBROWSE                1062
#define IDC_TMPFOLDER                   1063
#define IDC_DEFAULTTMP                  1064
#define IDC_TMPTITLE                    1065
#define IDC_LEFTBORDER                  1066
#define IDC_TOPBORDER                   1067
#define IDC_RIGHTBORDER                 1068
#define IDC_BOTTOMBORDER                1098
#define IDC_DEFAULTORIENTATION          1069
#define IDC_PORTRAIT                    1070
#define IDC_LANDSCAPE                   1071
#define IDC_DOUBLECOLUMN                1072
#define IDC_UNIT1                       1073
#define IDC_UNIT2                       1074
#define IDC_UNIT3                       1075
#define IDC_UNIT4                       1076
#define IDC_HEADER                      1077
#define IDC_FOOTER                      1078
#define IDC_PRINTFRAME                  1079
#define IDC_PREVIEW                     1080
#define IDC_DIVIDINGLINE                1081
#define IDC_MOREFILESQUIT               1081
#define IDC_PRINTFRAME2                 1082
#define IDC_LINENUMBER                  1083
#define IDC_PRINTFONT                   1084
#define IDC_FONTNAME                    1085
#define IDC_PAGESPRINTED                1087
#define IDC_TAGS                        1088
#define IDC_NOTEPADNL                   1089
#define IDC_LINENUMBERS                 1090
#define IDC_FULLROWEXTEND               1090
#define IDC_HEXADDRESSES                1091
#define IDC_HEXSEARCH                   1092
#define IDC_ENGLISH                     1093
#define IDC_SPANISH                     1094
#define IDC_FRENCH                      1095
#define IDC_GERMAN                      1096
#define IDC_AUTOLANG                    1097
#define IDC_WRAP_AT_RIGHT_BORDER        1099
#define IDC_WRAP_AT_COLUMN              1100
#define IDC_SHOW_SCROLLBAR              1101
#define IDC_NO_WRAP_OR_SCROLLBAR        1102
#define IDC_WRAP_COLUMN                 1103
#define IDC_WRAP_CHAR                   1104
#define IDC_WRAP_WORD1                  1105
#define IDC_WRAP_WORD2                  1106
#define IDC_REFRESHBKG                  1107
#define IDC_SETTINGSTAB                 1108
#define IDC_PROFILEMANAGER              1110
#define IDC_PROFILENAME                 1111
#define IDC_SAVEPERMANENTLY             1112
#define IDC_DRIVEPATHUNC                1113
#define IDC_ONETIMESETTING              1113
#define IDC_EXTENSIONS                  1114
#define IDC_AUTOPERMANENT               1115
#define IDC_CURRENTUSER                 1116
#define IDC_ALLUSERS                    1117
#define IDC_AUTO                        1118
#define IDC_CRLF                        1119
#define IDC_LF                          1120
#define IDC_CR                          1121
#define IDC_ANSICP                      1123
#define IDC_MACRONAME                   1123
#define IDC_MAXSCROLL                   1123
#define IDC_FONTSAMPLE_TEXT             1123
#define IDC_UNDOLIMIT                   1123
#define IDC_OEMCP                       1124
#define IDC_LIST1                       1124
#define IDC_MACROLIST                   1124
#define IDC_FONTSAMPLE_HEX              1124
#define IDC_TEXT                        1125
#define IDC_MACROINPUT                  1125
#define IDC_HEX                         1126
#define IDC_MACROREPLACE                1126
#define IDC_AUTOENCODING                1127
#define IDC_INSERTMODE                  1127
#define IDC_ANSI                        1128
#define IDC_COMMANDMODE                 1128
#define IDC_OEM                         1129
#define IDC_COMMANDLINE                 1129
#define IDC_EBCDIC                      1130
#define IDC_UTF8                        1131
#define IDC_UTF16LE                     1132
#define IDC_UTF16BE                     1133
#define IDC_SETMACRO                    1134
#define IDC_DELMACRO                    1135
#define IDC_MAP                         1136
#define IDC_ABBREV                      1137
#define IDC_CHANGEFONT_TEXT             1144
#define IDC_CHANGEFONT_HEX              1145
#define IDC_FONTNAME_TEXT               1146
#define IDC_FONTNAME_HEX                1147
#define IDC_PROFILETITLE                1148
#define IDC_BKUPTITLE1                  1149
#define IDC_BKUPTITLE2                  1150
#define IDC_BITMAPTITLE                 1151
#define IDC_BITMAPEDIT                  1152
#define IDC_SYSCOLOR                    1153
#define IDC_CHOOSECOLOR                 1154
#define IDC_FRAME                       1155
#define IDC_TABEXPANDDOMAINS            1156
#define IDC_TABEXPDOMAINTITLE           1157
#define IDC_CODEPAGESTITLE              1158
#define IDC_ANSICPTITLE                 1159
#define IDC_OEMCPTITLE                  1160
#define IDC_NEWPROFILE                  1161
#define IDC_DELPROFILE                  1162
#define IDC_DRIVEPATHUNCTITLE           1163
#define IDC_EXTENSIONSTITLE             1164
#define IDC_PROFILEACTIVATE             1166
#define IDC_GETSTRINGTITLE              1167
#define IDC_GETSTRINGSTRING             1168
#define IDC_SHELL                       1169
#define IDC_SHELLCOMMAND                1170
#define IDC_HELPURL                     1171
#define IDC_TABEXPANDWITHSLASH          1172
#define GER_OFFSET                      7000
#define ENG_OFFSET                      9000
#define SPA_OFFSET                      10000
#define FRA_OFFSET                      12000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         316
#define _APS_NEXT_CONTROL_VALUE         1173
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
